default_zone: public
firewalld_service_rules:
  http:
    service: http
    state: enabled
    zone: public
  https:
    service: https
    state: enabled
    zone: public

firewalld_port_rules:
  caddy:
    port: 9999
    protocol: tcp
    state: enabled
    zone: public
