---
acme_user: "acme"
acme_home: "/home/acme"
acme_email: "iana@pims.math.ca"
dehydrate_ca: "https://acme-staging.api.letsencrypt.org/directory"

# One list item per machine, multiple names for the same machine
# can be handled by space separating a single list item
# e.g.
#   ["a.example.com b.example.com", "c.example.com"]
# would generate two certificate, one for a & b and another for c
# see https://github.com/lukas2511/dehydrated/blob/master/docs/domains_txt.md
#
acme_domains: ["{{ inventory_hostname }}"]
acme_secrets: ['./secret/acme']
