ius_repo_rpm: "https://{{ ansible_distribution | lower }}{{ ansible_distribution_major_version}}.iuscommunity.org/ius-release.rpm"
ius_repofile_path: "ius.repo"
ius_repo_gpg_key_url: "https://dl.iuscommunity.org/pub/ius/IUS-COMMUNITY-GPG-KEY"

ius_python3_packages:
  - { name: 'python36u', state: 'latest' }
  - { name: 'python36u-pip', state: 'latest' }
