---
## Ban a user for ToS violation
- name: Get User Hash
  hosts: sharder
  become: true
  tasks:
    - name: Get user hash from name
      shell: "/usr/local/bin/findhash.php {{ user | mandatory }}"
      register: findhash_results
      delegate_to: "{{ groups['ssp'][0] }}"
      when: user is defined

    - name: Report user hash
      debug:
        msg: '{{ findhash_results.stdout_lines }}'

    - set_fact:
        userhash: '{{ findhash_results.stdout_lines | first }}'
      when: user is defined

    - name: Report user hash
      debug:
        msg: '{{ userhash }}'


    - name: Get the location of the user by hash
      shell: "/bin/python3 /srv/sharder/sharder/admin.py --find-user {{ userhash | mandatory }}"
      register: user_results
      when: userhash is defined

    - set_fact:
        userhub: "{{ user_results.stdout | regex_search(hub_regexp, '\\1') | first }}"
      vars:
        hub_regexp: "{{ userhash | mandatory  + '\\s+' + '(((?!-)[a-zA-Z0-9-]{1,63}(?<!-)\\.)+[a-zA-Z]{2,63}$)' }}"
      ignore_errors: true

    - name: Fail if hub not found
      fail:
        msg: Hub not found
      when:
        userhub is not defined

    - name: Check if hub exists
      fail:
        msg: User hub not found
      when: userhub not in groups['hub']

    - name: Set user storage to readonly
      zfs:
        name: "tank/home/{{ userhash | mandatory }}"
        state: present
        extra_zfs_properties:
          readonly: on
      delegate_to: "{{ userhub }}"

    - name: Stop user container
      docker_container:
        name: 'jupyter-{{ userhash | mandatory }}'
        state: absent
      delegate_to: "{{ userhub }}"
