---
## Calculates the hash of a JupyterHub user
- name: Get User Hash
  hosts: ssp
  become: true
  tasks:
    - name: Get user hash
      shell: "/usr/local/bin/findhash.php {{ user | mandatory }}"
      register: findhash_results

    - name: Get the location of the user
      shell: "/bin/python3 /srv/sharder/sharder/admin.py --find-user {{ findhash_results.stdout }}"
      delegate_to: "{{ groups['sharder'][0] }}"
      register: results

    - name: Report user
      debug:
        msg: "{{ results.stdout_lines }}"
