---

- name: Jupyter Setup
  hosts: jupyter
  become: true

  roles:
    - { role: elrepo-kernel,               tags: ["elrepo"] }
    - { role: hostname,                    tags: ["setup", "hostname"] }
    - { role: base-packages,               tags: ["setup", "base-packages"] }
    - { role: ansible-role-selinux,        tags: ["selinux"] }
    - { role: ansible-role-firewalld,      tags: ["firewalld"] }
    - { role: ansible-sshd,                tags: ["sshd"] }
    - { role: ansible-sudo,                tags: ["sudo"] }
    - { role: ansible-role-apache,         tags: ["httpd"] }
    - { role: dehydrate-letsencrypt,       tags: ["letsencrypt"] }
    - { role: callysto-html,               tags: ["httpd"] }
    - { role: zfs,                         tags: ["zfs"] }
