---
- name: Fix sudo TTY
  hosts: jupyter
  tasks:
    - name: Disable sudo requiretty
      lineinfile:
        dest: /etc/sudoers
        line: 'Defaults    requiretty'
        state: absent
      become: true
      vars:
          ansible_ssh_pipelining: no
      tags: always

- name: Jupyter Setup
  hosts: jupyter
  become: true

  roles:
    - { role: elrepo-kernel,               tags: ["setup", "elrepo"] }
    - { role: hostname,                    tags: ["setup", "hostname"] }
    - { role: base-packages,               tags: ["setup", "base-packages"] }
    - { role: ssh-public-keys,             tags: ["setup", "ssh"] }
    - { role: ansible-role-selinux,        tags: ["selinux"] }
    - { role: ansible-role-firewalld,      tags: ["firewalld"] }
    - { role: ansible-sshd,                tags: ["sshd"] }
    - { role: ansible-sudo,                tags: ["sudo"] }
    - { role: ansible-role-apache,         tags: ["httpd"] }
    - { role: dehydrate-letsencrypt,       tags: ["letsencrypt"] }
    - { role: callysto-html,               tags: ["httpd"] }
    - { role: zfs,                         tags: ["zfs"] }
    - { role: ius-python3,                 tags: ["python3"] }
    - { role: ansible-role-docker,         tags: ["docker"] }
    - { role: dockerhub,                   tags: ["docker", "dockerhub"] }
    - { role: jupyterhub,                  tags: ["jupyterhub"] }
    - { role: ssp-idp-multi,               tags: ["simplesaml"] }
