---
## Tasks to manage a JupyterHub user's quota
- name: ZFS Quota Tasks
  hosts: hub
  become: true
  tasks:
    - name: Set quota for user
      shell: zfs set refquota={{ refquota | mandatory }} tank/home/{{ user | mandatory }}
      when:
        - set_quota is defined

    - name: Get ZFS Data
      zfs_facts:
        name: tank/home
        recurse: yes
        type: filesystem

    - name: Report ZFS
      shell: zfs get used,refquota -o property,value tank/home/{{ user }}
      register: zfs_result
      when: user != ""

    - name: Show value of ZFS
      debug:
        var: zfs_result.stdout_lines
