- name: restart httpd
  service:
    name: "{{ apache_service | default('httpd') }}"
    state: restarted
  become: yes

- name: reload httpd
  service:
    name: "{{ apache_service | default('httpd') }}"
    state: reloaded
  become: yes
