---
# Tasks for base package installation (RedHat)
- name: Setup epel repo
  yum:
    name: "epel-release"
    state: present
    update_cache: yes
  tags: setup

- name: Install base packages
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
    update_cache: yes
  tags: setup
  with_items: '{{ base_packages }}'
