---
- name: Check if IUS repo is already configured
  stat: path= {{ ius_repofile_path }}
  register: ius_repofile_result

- name: Add IUS repo
  yum:
    name: "{{ ius_repo_rpm }}"
    state: present
  register: result
  until: '"failed" not in result'
  retries: 5
  delay: 10
  when: not ius_repofile_result.stat.exists
  ignore_errors: "{{ ansible_check_mode }}"

- name: Install python3
  yum:
    name: '{{ item.name }}'
    state: '{{ item.state }}'
  with_items: '{{ ius_python3_packages }}'

- name: Symlink python3
  file:
    src: '/usr/bin/python3.6'
    dest: '/usr/bin/python3'
    state: link
