- name: Ensure php packages installed
  yum:
    state: present
    update_cache: yes
    name:
      - php72u-cli
      - mod_php72u
      - php72u-pdo
      - php72u-xml
      - php72u-soap
      - php72u-pecl-apcu
      - php72u-mbstring
      - php72u-json
      - php72u-gd
  become: yes
  notify:
    - restart httpd
