---
# Manages a Sharder installation.
# This shouldn't be run on its own.
- name: Validate sharder configuration
  hosts: sharder
  become: true
  tasks:
    - name: Ensure callysto_ssl_cert_dir is set
      assert:
        that: >-
          callysto_ssl_cert_dir != ""
        msg: "Must set callysto_ssl_cert_dir"

    - name: Ensure ssp_domain is set
      assert:
        that: >-
          jupyterhub_authenticator != 'shib' or (ssp_domain is defined and ssp_domain != '')
        msg: "Must set ssp_domain when using shib authenticator"

    - name: Ensure hub_metrics is set
      assert:
        that: >-
          hub_metrics is defined
        msg: "Must set hub_metrics to true or false"

- name: Ensure sudo is configured correctly
  hosts: sharder
  become: true
  tasks:
    # Settings are defined in
    # group_vars/<group>/sudo.yml
    - name: Configure sudo
      tags: ["sudo", "always"]
      include_role:
        name: sudo
      vars:
          ansible_ssh_pipelining: no

- name: Install and configure the sharder
  hosts: sharder
  become: true
  tasks:
    - name: Ensure hostname is set
      tags: ["hostname"]
      include_role:
        name: hostname

    # Add relevant keys to `ssh_public_keys`
    # in either host_vars, group_vars, or local_vars.
    - name: Manage SSH public keys
      tags: ["ssh"]
      include_role:
        name: ssh-public-keys

    # This also installs EPEL
    - name: Ensure base packages are installed
      tags: ["base-packages"]
      include_role:
        name: base-packages

    - name: Configure SELinux
      tags: ["selinux"]
      include_role:
        name: selinux
      vars:
        selinux_policy: targeted
        selinux_state: permissive

    # Enabled services are defined in
    # group_vars/hub/firewalld.yml
    - name: Ensure firewalld service is running
      tags: ["firewalld"]
      include_role:
        name: firewalld

    # Configuration is stored in
    # group_vars/<group>/ssh.yml.
    - name: Ensure sshd is installed and running
      tags: ["sshd"]
      include_role:
        name: sshd

    - name: Copy SSL certificates
      include_role:
        name: callysto-ssl

    # Configuration is stored in
    # group_vars/<group>/httpd.yml
    - name: Manage Apache
      tags: ["httpd"]
      include_role:
        name: apache

    - name: Manage Python3
      tags: ["python", "python3"]
      include_role:
        name: ius-python3

    - name: Manage Shibboleth
      tags: ["shib"]
      include_role:
        name: shibboleth
      when: jupyterhub_authenticator == 'shib'

    - name: Manage Callysto html repo
      include_role:
        name: callysto-html

    - name: Manage Sharder
      tags: ["sharder"]
      include_role:
        name: sharder

    - name: Manage rrsync script
      tags: ["ssh", "rrsync", "backup"]
      include_role:
        name: rrsync

    #- name: Prometheus node-exporter
    #  tags: ["stats","prometheus"]
    #  include_role:
    #    name: prometheus-node-exporter
    #  vars:
    #    prometheus_node_exporter_config_flags:
    #       'web.listen-address': '127.0.0.1:9100'
    #       'log.level': 'info'
    #  when: hub_metrics
