---
- name: Restart Sharder
  systemd:
    name: sharder
    state: restarted
    daemon_reload: yes

- name: Restart Apache
  systemd:
    name: "{{ apache_service | default('httpd') }}"
    state: restarted
    daemon_reload: yes
