---
- name: deamon reload
  command: systemctl daemon-reload

- name: Restart JupyterHub
  service:
    name: jupyterhub
    state: restarted

- name: Restart CHP
  service:
    name: configurable-http-proxy
    state: restarted

- name: restart httpd
  service:
    name: "{{ apache_service | default('httpd') }}"
    state: restarted
  become: yes
