---
- name: Add public keys for external users
  authorized_key:
    user: '{{ item.value.user }}'
    state: '{{ item.value.state }}'
    key: '{{ item.value.public_key }}'
  with_dict: "{{ ssh_public_keys }}"
  when: ssh_public_keys is defined
