---
- name: restart apache
  service:
    name: "{{ apache_service | default('httpd') }}"
    state: restarted
  become: yes

- name: Copy landing page templates
  shell: "rm -rf {{ callysto_html_dir.dest }} && mkdir {{ callysto_html_dir.dest }} && git archive {{ callysto_landing_branch }} | tar -x -C {{ callysto_html_dir.dest }}"
  args:
    chdir: '{{ callysto_html_dir.src }}'
