jupyterhub_authenticator: "syzygyauthenticator.google.SyzygyGoogleOAuthenticator"
jupyterhub_authenticator_options:

  - conf_object: 'SyzygyAuthenticator.user_id'
    value: '{{ jupyterhub_user_uid }}'
  - conf_object: 'SyzygyAuthenticator.homedir_string'
    value: "'/tank/home/USERNAME'"
  - conf_object: 'SyzygyAuthenticator.create_homedir_cmd'
    value: "['/opt/syzygyauthenticator/zfs-homedir.sh', 'USERNAME', 'jupyter']"
  - conf_object: 'SyzygyAuthenticator.create_system_users'
    value: 'False'
  - conf_object: 'SyzygyAuthenticator.create_user_homedir'
    value: 'True'
  - conf_object: 'SyzygyGoogleOAuthenticator.client_id'
    value: "os.environ['OAUTH_CLIENT_ID']"
  - conf_object: 'SyzygyGoogleOAuthenticator.client_secret'
    value: "os.environ['OAUTH_CLIENT_SECRET']"
  - conf_object: 'SyzygyGoogleOAuthenticator.callback_url'
    value: "os.environ['OAUTH_CALLBACK_URL']"

syzygy_html_logout_message: "You have been logged out of your Jupyter but you are still be signed in to google"
syzygy_html_logout_message_extra: '<a href="https://accounts.google.com/Logout">SIGN OUT OF GOOGLE</a>'
