ssp_develop: False

# Version 1.17.8
ssp_ver: 1.17.8
ssp_sha256: 22e4210e06f9fba1e528cebcd38d788a944e2737330fae938e1c30a988a16465

ssp_url: https://github.com/simplesamlphp/simplesamlphp/releases/download/v{{ ssp_ver  }}/simplesamlphp-{{ ssp_ver  }}.tar.gz

ssp_authoauth2_version: 'v2.0.0'

ssp_path: /var
ssp_prefix: simplesamlphp-
ssp_dir: "{{ ssp_path  }}/{{ ssp_prefix  }}{{ ssp_ver  }}"
ssp_tmp_dir: /tmp/ssp
ssp_www_user: apache
ssp_www_group: apache

ssp_cron_daily_cmd: "curl --silent -k 'https://localhost/simplesaml/module.php/cron/cron.php?key={{ ssp_refresh_key  }}&tag=daily' > /dev/null 2>&1"
ssp_cron_hourly_cmd: "curl --silent -k 'https://localhost/simplesaml/module.php/cron/cron.php?key={{ ssp_refresh_key  }}&tag=hourly' > /dev/null 2>&1"
#ssp_refresh_key: E1jvd1TbqSHL

ssp_theme_install: True

# False by default until install is done
ssp_installed_now: False

# ssp theme
ssp_theme_name: "default"
ssp_theme_repo: ""
ssp_theme_version: ""
ssp_theme_dir: ""

# hash the usernames
ssp_hash_usernames: True

# Semi-hack to know when ssp is installed standalone and not with jupyterhub all-in-one
ssp_standalone: False
