---
- name: Install zfs-release
  yum:
    name: '{{ zfs_release_rpm }}'
    state: present
  register: zfs_repo
  notify:
    - Remove existing zfs packages

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Clean yum if zfs repo pkg installed
  command: yum clean all
  when: zfs_repo.changed

- name: Install zfs kernel module
  yum:
    name: zfs
    state: present
    update_cache: yes
  notify:
    - Modprobe zfs

- name: Ensure the ZFS kernel module is loaded
  modprobe:
    name: zfs

- name: Flush ZFS Handlers
  meta: flush_handlers

- name: Check zpool {{ zfs_pool_name }} exsits
  zpool_facts: pool={{ zfs_pool_name }}
  register: zpool_exist
  ignore_errors: yes

- name: Remove {{ zfs_pool_name }} mount point
  file:
    state: absent
    path: '/{{ zfs_pool_name }}'
  when: zpool_exist.failed ==  true

- name: Create {{ zfs_pool_name }} zpool
  notify:
   - Start zfs
  command: /sbin/zpool create -f {{ zfs_pool_name }} mirror "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_{{ zfs_disk_1[0:20] }}" "/dev/disk/by-id/scsi-0QEMU_QEMU_HARDDISK_{{ zfs_disk_2[0:20] }}"
  args:
    creates: "/{{ zfs_pool_name }}"
  when: zfs_disk_1 != "" and zfs_disk_2 != ""

- name: Create ZFS containers
  command: "/sbin/zfs create {{ zfs_pool_name }}/{{ item }}"
  args:
    creates: "/{{ zfs_pool_name }}/{{ item }}"
  with_items: "{{ zfs_containers }}"
  when: zfs_disk_1 != "" and zfs_disk_2 != ""
